# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Info(object):
    def setupUi(self, Info):
        Info.setObjectName("Info")
        Info.resize(338, 517)
        self.centralwidget = QtWidgets.QWidget(Info)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 301, 471))
        self.textBrowser.setObjectName("textBrowser")
        Info.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Info)
        self.statusbar.setObjectName("statusbar")
        Info.setStatusBar(self.statusbar)

        self.retranslateUi(Info)
        QtCore.QMetaObject.connectSlotsByName(Info)

    def retranslateUi(self, Info):
        _translate = QtCore.QCoreApplication.translate
        Info.setWindowTitle(_translate("Info", "Info"))
        self.textBrowser.setHtml(_translate("Info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ChatBot Nedir?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ChatBot, yapay zeka teknolojisi kullanılarak oluşturulmuş bir sohbet programıdır. İster gece ister gündüz, istediğiniz zaman size eşlik edebilir, sorularınıza yanıt verebilir ve hatta ders notlarınız hakkında yardımcı olabilir. Bilgiye ulaşmanın en kolay ve hızlı yolu olan ChatBot, sizinle etkileşim kurarak bilgi paylaşımını sağlar.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ChatBot Nasıl Çalışır?</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ChatBot, kullanıcıdan gelen metni analiz eder ve en uygun yanıtı verir. Bu, genellikle bir yapay zeka modeli kullanılarak gerçekleştirilir. Kullanıcı, altta bulunan metin giriş çubuğuna bir soru veya ifade yazarak sohbete başlar. ChatBot, bu metni analiz eder ve bir yanıt oluşturur. Bu yanıt, kullanıcıya görsel bir arayüz aracılığıyla sunulur.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ChatBot’un işlevselliği, üstte bulunan <span style=\" font-weight:600;\">Kopyala</span> ve <span style=\" font-weight:600;\">Temizle</span> butonları ile daha da genişletilmiştir. <span style=\" font-weight:600;\">Kopyala</span> butonu, sohbet geçmişini kopyalamanıza olanak sağlar. Bu, özellikle önemli bilgileri saklamak veya başkalarıyla paylaşmak istediğinizde kullanışlıdır. <span style=\" font-weight:600;\">Temizle</span> butonu ise sohbet geçmişini temizler, böylece yeni bir sohbete temiz bir sayfadan başlayabilirsiniz.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">ChatBot’un Faydaları</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ChatBot, bilgiye hızlı ve kolay bir şekilde ulaşmanızı sağlar. Bir konu hakkında bilgi ararken veya bir problemi çözerken, ChatBot size anında yardımcı olabilir. Ayrıca, ChatBot’un 7/24 kullanılabilir olması, her zaman yardımcı olabilecek bir arkadaşa sahip olduğunuz anlamına gelir. İster gece geç saatlerde ders çalışırken, ister yeni bir konuyu araştırırken, ChatBot her zaman yanınızdadır.</p></body></html>"))
